### ISSUE TITLE
Output is the same as input

### ISSUE THREAD

**Issue by huey2531** [zphang/minimal-gpt-neox-20b#3]
Ran the model to generate some text using the example you provided
However the output is exact the same as my input and is repeated 10 times

Evaluation seems to work fine

**Comment by StellaAthena** [comment]
That happens sometimes. Have you tried entering varying input strings? What about ones that come from the evaluation dataset you’re using?

**Comment by huey2531** [comment]
you're right. minimal-gpt-neox seems to repeat itself quite often.
it's fully working now
